# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='media_img', verbose_name='Фото')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='media_img', verbose_name='Фото')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('price', models.FloatField(blank=True, verbose_name='Плата за участие')),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content_app.BoardGame', verbose_name='Игра')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='media_img', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('recipe_type', models.BooleanField(verbose_name='Вид рецепта')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='media_img', verbose_name='Фото')),
                ('volume', models.IntegerField(blank=True, verbose_name='В наличии')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(verbose_name='Объем, г')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.Ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.Recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
