# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
