# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_auto_20170913_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
