# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_app', '0008_attendedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.Recipe', verbose_name='Еда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='FavouriteGame',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteGame',
        ),
    ]
